version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  ubuntu-2004:
    machine:
      image: ubuntu-2004:202010-01
  # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
  macos-1015:
    macos:
      xcode: 12.4.0
  macos-1100:
    macos:
      xcode: 12.5.1

commands:
  gem_cache:
    steps:
      - restore_cache:
          keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "gemfile.lock" }}
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-
          - v1-gem-cache-{{ arch }}-
      - run: bundle install
      - run: bundle clean --force
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "gemfile.lock" }}
  export_env_vars:
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "BUNDLE_GEMFILE=.gemfile" >> $BASH_ENV

jobs:
  pre_commit:
    executor: ubuntu-2004
    steps:
      - export_env_vars
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: pip3 install pre-commit
      #- run: pre-commit run --all-files --verbose
      - run: git remote add original https://github.com/mozilla-platform-ops/ronin_puppet.git
      - run: git fetch --all
      - run: pre-commit run --from-ref original/master --to-ref HEAD --verbose
  r10k_install:
    executor: ubuntu-2004
    steps:
      - export_env_vars
      - checkout
      - run: BUNDLE_GEMFILE=.gemfile bundle install
      - run: BUNDLE_GEMFILE=.gemfile bundle exec r10k puppetfile install --moduledir=/tmp/r10k_module_test -v --force
  kitchen_converge_and_verify:
    executor: ubuntu-2004
    parameters:
      kitchen_target:
        type: string
    steps:
      - export_env_vars
      - checkout
      - run: BUNDLE_GEMFILE=.gemfile bundle install
      - run:
          command: BUNDLE_GEMFILE=.gemfile KITCHEN_YAML=.kitchen_configs/kitchen.docker.yml bundle exec kitchen converge << parameters.kitchen_target >>
          no_output_timeout: 30m
      - run: BUNDLE_GEMFILE=.gemfile KITCHEN_YAML=.kitchen_configs/kitchen.docker.yml bundle exec kitchen verify << parameters.kitchen_target >>
  macos_test:
    executor: macos-1015
    steps:
      - export_env_vars
      - checkout
      - run: sw_vers
      - run: id
      - run: sudo id
      - run: bundle install
      - run: KITCHEN_YAML=.kitchen_configs/kitchen.macos.circleci.yml bundle exec kitchen converge test
  macos_test2:
    executor: macos-1100
    steps:
      - export_env_vars
      - checkout
      - run: sw_vers
      - run: id
      - run: sudo id
      - slack/status:
          fail_only: false

workflows:
  ci_test:
    jobs:
      - pre_commit
      - r10k_install
      - macos_test
#      - macos_test2:
#         context: slack-secrets
#      - kitchen_converge_and_verify:
#          matrix:
#            parameters:
#              # "maas-region" and "maas-rack" removed as we're not using them currently
#              kitchen_target: ["bitbar", "linux"]
