version: 2.1

orbs:
  slack: circleci/slack@4.4.2

executors:
  ubuntu-2004:
    machine:
      image: ubuntu-2004:202010-01
  # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
  macos-1015:
    macos:
      xcode: 12.4.0
  macos-1100:
    macos:
      xcode: 12.5.1

jobs:
  pre_commit:
    executor: ubuntu-2004
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: pip3 install pre-commit
      #- run: pre-commit run --all-files --verbose
      - run: git remote add original https://github.com/mozilla-platform-ops/ronin_puppet.git
      - run: git fetch --all
      - run: pre-commit run --from-ref original/master --to-ref HEAD --verbose
  r10k_install:
    executor: ubuntu-2004
    steps:
      - checkout
      - run: BUNDLE_GEMFILE=.gemfile bundle install
      - run: BUNDLE_GEMFILE=.gemfile bundle exec r10k puppetfile install --moduledir=/tmp/r10k_module_test -v --force
  kitchen_converge_and_verify:
    executor: ubuntu-2004
    parameters:
      kitchen_target:
        type: string
    steps:
      - checkout
      - run: BUNDLE_GEMFILE=.gemfile bundle install
      - run:
          command: BUNDLE_GEMFILE=.gemfile KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen converge << parameters.kitchen_target >>
          no_output_timeout: 30m
      - run: BUNDLE_GEMFILE=.gemfile KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen verify << parameters.kitchen_target >>
  macos_test:
    executor: macos-1015
    steps:
      - checkout
      - run: sw_vers
      - run: id
      - run: sudo id
  macos_test2:
    executor: macos-1100
    steps:
      - checkout
      - run: sw_vers
      - run: id
      - run: sudo id
workflows:
  ci_test:
    jobs:
      - pre_commit
      - r10k_install
      - macos_test
      - macos_test2
#      - kitchen_converge_and_verify:
#          matrix:
#            parameters:
#              # "maas-region" and "maas-rack" removed as we're not using them currently
#              kitchen_target: ["bitbar", "linux"]
